web:
  build: .
  command: /run.sh
  links:
   - statsd
   - grafana
  ports:
   - "80:80"


statsd:
  image: shakr/statsd-influxdb
  ports:
    - "8125:8125/udp"
  env_file:
    - env.statsd
  links:
    - influxdb

influxdb:
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb